handle passing include[]=user for user files
fixes: CNVS-15676

this was failing with:
undefined method `user_user_url'

because it was trying do a polymorphic_url in:
lib/api/v1/user.rb:107:in `user_display_json'

test plan:
hit the api at:
/api/v1/folders/xx/folders?include[]=user

where xx is the id of a folder that belongs to a
user. it should not return an error.

Change-Id: I48f4b4d368f65b58e9ebb6e9fd3bc508b2be5c60
Reviewed-on: https://gerrit.instructure.com/41411
Reviewed-by: Jeremy Stanley <jeremy@instructure.com>
Product-Review: Jeremy Stanley <jeremy@instructure.com>
Tested-by: Jenkins <jenkins@instructure.com>
Product-Review: Ryan Shaw <ryan@instructure.com>
QA-Review: Clare Strong <clare@instructure.com>